{application,websocket,
             [{description,"Cowboy websocket example."},
              {vsn,"1"},
              {modules,[cmd,taclient,toppage_handler,websocket,websocket_app,
                        websocket_sup,ws_handler,ws_handler_1,ws_handler_2,
                        ws_handler_3]},
              {registered,[websocket_sup]},
              {applications,[kernel,stdlib,cowboy]},
              {mod,{websocket_app,[]}},
              {env,[]}]}.
